version: '3'

services:
  backend:
    image: "backend"
    hostname: "backend"
    container_name: "backend"
    environment:
      - PORT=80
    build: 
      context: ./server
    ports:
      - 80:80
  db:
    image: mysql
    container_name: db
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=db
    ports:
      - 3306:3306